### PR TITLE
Budapest Zoo and pandas added

### PR DESCRIPTION
**Pull request by Balathruin**
Added Budapest Zoo
Added Auróra
Added Bendegúz

### CODE REVIEW

**Comment by Balathruin** [comment]
Spotted some issues, I'll be updating this shortly.
Also working on correcting Jászberény Zoo.

**Comment by wwoast** [comment]
Oh, thank you so much for adding these sweethearts, and for fixing any mistakes I have with the Hungary data.

**Comment by Balathruin** [comment]
Quick question. Is it possible to add pandas without knowing the current zoo? I could add Ambrus and Haiku for Budapest Zoo, but they have been moved since. Budapest Zoo had a cub too, but also moved. Jászberény Zoo originally had two sisters, however Svea was exchanged for Shifu. Lea had two cubs back in 2018 aswell.
I could not find public information where to and from Budapest Zoo got the animals. Zero clue if it is possible to request data like that.

**Comment by wwoast** [comment]
I'll follow up with you privately on how I source information on these pandas.

As for the animals where we don't know where they went -- if you have photos, let's add them to the most recent zoo they were seen at. We can slowly push towards correct information if we've collected enough of it in one place!

These updates look fantastic -- I'm so grateful for photos and info for animals that I don't yet have. I did notice a handful of photos where you weren't the photographer, but as long as these are public or you're sure they don't mind the links from RPF, it should be OK.

Finally, if the photos are large resolution there may be page layout issues. However I'm happy to mirror and resize photos manually if I need to (while preserving author info).

Cheers!
Justin

**Comment by Balathruin** [comment]
Do I need 'apostrophes' or (brackets) for links like that? Couldn't find an example.

**Comment by wwoast** [comment]
Interesting. It looks like `%` in the text files gets read as an escape character by the Python `ConfigParser` library. If you change it to `%%` then it looks like it will work.

You also have a leading zero in the `birthday:` for Ambrus, which fails the consistency check with his `location.1` value. If you fix both of those things, this will be mergeable!

**Review by wwoast — APPROVED** [review]

**Pull request merged**
