### PR TITLE
Red pandas in the UK and France; passing of Frisco

### PR DESCRIPTION
**Pull request by akapanredpanda**
My first day using GitHub. I've added some red pandas from three zoos in the UK and Zoo de Lille, France. I've also updated the data of Frisco  and her passing.

### CODE REVIEW

**Comment by wwoast** [comment]
Thank you so much for your support and adding these animals to RPF! I'm really grateful for the information and photos, and it takes a ton of tedious work to grab all the extra info for Japanese names and lat/long. Really appreciate it!

I'll shortly push some updates to this branch to fix some issues:
- Some of the URIs with `%` in them need to be `%%`. This seems to be a limitation of Python's ConfigParser library.
- fbcdn URLs for photos are not guaranteed to work long term. There are three image URIs of these from a previous PR and sadly they're all broken. I can try and mirror them potentially, if you are confident that would be permitted by the owners.
- I try and not do leading zeroes on dates: `2020/02/09` => `2020/2/9`
- Is 1262 just a panda we don't have a name or background for?

Thank you :)
Justin

**Comment by wwoast** [comment]
One more question -- in the [mosaic of photos you found for Amba](https://scontent.fvix14-1.fna.fbcdn.net/v/t1.6435-9/135472253_4056535774374842_1423304955129456933_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=Vf0O0rN41mIAX8co2CJ&_nc_oc=AQmU5NvNEi8Umsg1bewI0t1vrNR2RC_gCugpCGd1v9msSix_43JB4-XataTd1pkVTJs&_nc_ht=scontent.fvix14-1.fna&oh=8f8f30fb3b0f5e65dec599210a5aba52&oe=6093A6E8), do you know who the babies are?

**Comment by akapanredpanda** [comment]
> Thank you so much for your support and adding these animals to RPF! I'm really grateful for the information and photos, and it takes a ton of tedious work to grab all the extra info for Japanese names and lat/long. Really appreciate it!
> 
> I'll shortly push some updates to this branch to fix some issues:
> 
> * Some of the URIs with `%` in them need to be `%%`. This seems to be a limitation of Python's ConfigParser library.
> * fbcdn URLs for photos are not guaranteed to work long term. There are three image URIs of these from a previous PR and sadly they're all broken. I can try and mirror them potentially, if you are confident that would be permitted by the owners.
> * I try and not do leading zeroes on dates: `2020/02/09` => `2020/2/9`
> * Is 1262 just a panda we don't have a name or background for?
> 
> Thank you :)
> Justin

Hi Justin! You're welcome, and thank you for the advices.

Since I just found the photos at the pages of the zoos on Facebook, I don't know if the owners would permit their usage.

About the panda 1262, the only information I have is given in the [description of the photo](https://www.facebook.com/bhamwildlifeconservationpark/photos/a.909971245697993/4056535771041509/) of their mother, Amba, when she died: "She formed a successful breeding pair with our male, Mo, and between them they had 4 offspring; Mambo, Ruby, Rose and last year's as yet unnamed cub."

**Comment by akapanredpanda** [comment]
> One more question -- in the [mosaic of photos you found for Amba](https://scontent.fvix14-1.fna.fbcdn.net/v/t1.6435-9/135472253_4056535774374842_1423304955129456933_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=Vf0O0rN41mIAX8co2CJ&_nc_oc=AQmU5NvNEi8Umsg1bewI0t1vrNR2RC_gCugpCGd1v9msSix_43JB4-XataTd1pkVTJs&_nc_ht=scontent.fvix14-1.fna&oh=8f8f30fb3b0f5e65dec599210a5aba52&oe=6093A6E8), do you know who the babies are?

Unfortunately, I don't know exactly which babies they are.

**Comment by wwoast** [comment]
I might be able to fill in some details from the Facebook history and photo descriptions, but my available data is only partial after ~2018. This won't improve unless I get help from folks in the various geographic zoological associations.

**Pull request merged**
